spring.application.name=authentication-app

server.port=8083

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/authentication_application
spring.datasource.username=root
spring.datasource.password=0417@2003

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


jwt.token.validity=900000
jwt.secret=yd10l/Wqe86E4xrtIrHGxpqVYQa1WuqOFbR/7ob7gxs2dfJ626Ve/7N8WgSOH7L9lg+fTOFbj+p3I4iXGbArog==
jwt.issuer=api.substring.com
jwt.access.til.seconds=3600
jwt.refresh.til.seconds=86400
jwt.refresh.cookie.name=refreshToken
jwt.cookie.secure=true
jwt.cookie.http.only=true
jwt.cookie.same.site=lax
jwt.cookie.domain=localhost
